using System;
using System.Collections.Generic;
using System.Text;

namespace DataSources
{
    public static class ListArtistsData
    {
        public static List<Artist> ListArtists = new List<Artist>
        {
            new Artist(1, "AC/DC"),
            new Artist(2, "Accept"),
            new Artist(3, "Aerosmith"),
            new Artist(4, "Alanis Morissette"),
            new Artist(5, "Alice In Chains"),
            new Artist(6, "Antônio Carlos Jobim"),
            new Artist(7, "Apocalyptica"),
            new Artist(8, "Audioslave"),
            new Artist(9, "BackBeat"),
            new Artist(10, "Billy Cobham"),
            new Artist(11, "Black Label Society"),
            new Artist(12, "Black Sabbath"),
            new Artist(13, "Body Count"),
            new Artist(14, "Bruce Dickinson"),
            new Artist(15, "Buddy Guy"),
            new Artist(16, "Caetano Veloso"),
            new Artist(17, "Chico Buarque"),
            new Artist(18, "Chico Science & Nação Zumbi"),
            new Artist(19, "Cidade Negra"),
            new Artist(20, "Cláudio Zoli"),
            new Artist(21, "Various Artists"),
            new Artist(22, "Led Zeppelin"),
            new Artist(23, "Frank Zappa & Captain Beefheart"),
            new Artist(24, "Marcos Valle"),
            new Artist(25, "Milton Nascimento & Bebeto"),
            new Artist(26, "Azymuth"),
            new Artist(27, "Gilberto Gil"),
            new Artist(28, "João Gilberto"),
            new Artist(29, "Bebel Gilberto"),
            new Artist(30, "Jorge Vercilo"),
            new Artist(31, "Baby Consuelo"),
            new Artist(32, "Ney Matogrosso"),
            new Artist(33, "Luiz Melodia"),
            new Artist(34, "Nando Reis"),
            new Artist(35, "Pedro Luís & A Parede"),
            new Artist(36, "O Rappa"),
            new Artist(37, "Ed Motta"),
            new Artist(38, "Banda Black Rio"),
            new Artist(39, "Fernanda Porto"),
            new Artist(40, "Os Cariocas"),
            new Artist(41, "Elis Regina"),
            new Artist(42, "Milton Nascimento"),
            new Artist(43, "A Cor Do Som"),
            new Artist(44, "Kid Abelha"),
            new Artist(45, "Sandra De Sá"),
            new Artist(46, "Jorge Ben"),
            new Artist(47, "Hermeto Pascoal"),
            new Artist(48, "Barão Vermelho"),
            new Artist(49, "Edson, DJ Marky & DJ Patife Featuring Fernanda Porto"),
            new Artist(50, "Metallica"),
            new Artist(51, "Queen"),
            new Artist(52, "Kiss"),
            new Artist(53, "Spyro Gyra"),
            new Artist(54, "Green Day"),
            new Artist(55, "David Coverdale"),
            new Artist(56, "Gonzaguinha"),
            new Artist(57, "Os Mutantes"),
            new Artist(58, "Deep Purple"),
            new Artist(59, "Santana"),
            new Artist(60, "Santana Feat. Dave Matthews"),
            new Artist(61, "Santana Feat. Everlast"),
            new Artist(62, "Santana Feat. Rob Thomas"),
            new Artist(63, "Santana Feat. Lauryn Hill & Cee-Lo"),
            new Artist(64, "Santana Feat. The Project G&B"),
            new Artist(65, "Santana Feat. Maná"),
            new Artist(66, "Santana Feat. Eagle-Eye Cherry"),
            new Artist(67, "Santana Feat. Eric Clapton"),
            new Artist(68, "Miles Davis"),
            new Artist(69, "Gene Krupa"),
            new Artist(70, "Toquinho & Vinícius"),
            new Artist(71, "Vinícius De Moraes & Baden Powell"),
            new Artist(72, "Vinícius De Moraes"),
            new Artist(73, "Vinícius E Qurteto Em Cy"),
            new Artist(74, "Vinícius E Odette Lara"),
            new Artist(75, "Vinicius, Toquinho & Quarteto Em Cy"),
            new Artist(76, "Creedence Clearwater Revival"),
            new Artist(77, "Cássia Eller"),
            new Artist(78, "Def Leppard"),
            new Artist(79, "Dennis Chambers"),
            new Artist(80, "Djavan"),
            new Artist(81, "Eric Clapton"),
            new Artist(82, "Faith No More"),
            new Artist(83, "Falamansa"),
            new Artist(84, "Foo Fighters"),
            new Artist(85, "Frank Sinatra"),
            new Artist(86, "Funk Como Le Gusta"),
            new Artist(87, "Godsmack"),
            new Artist(88, "Guns N' Roses"),
            new Artist(89, "Incognito"),
            new Artist(90, "Iron Maiden"),
            new Artist(91, "James Brown"),
            new Artist(92, "Jamiroquai"),
            new Artist(93, "JET"),
            new Artist(94, "Jimi Hendrix"),
            new Artist(95, "Joe Satriani"),
            new Artist(96, "Jota Quest"),
            new Artist(97, "João Suplicy"),
            new Artist(98, "Judas Priest"),
            new Artist(99, "Legião Urbana"),
            new Artist(100, "Lenny Kravitz"),
            new Artist(101, "Lulu Santos"),
            new Artist(102, "Marillion"),
            new Artist(103, "Marisa Monte"),
            new Artist(104, "Marvin Gaye"),
            new Artist(105, "Men At Work"),
            new Artist(106, "Motörhead"),
            new Artist(107, "Motörhead & Girlschool"),
            new Artist(108, "Mônica Marianno"),
            new Artist(109, "Mötley Crüe"),
            new Artist(110, "Nirvana"),
            new Artist(111, "O Terço"),
            new Artist(112, "Olodum"),
            new Artist(113, "Os Paralamas Do Sucesso"),
            new Artist(114, "Ozzy Osbourne"),
            new Artist(115, "Page & Plant"),
            new Artist(116, "Passengers"),
            new Artist(117, "Paul D'Ianno"),
            new Artist(118, "Pearl Jam"),
            new Artist(119, "Peter Tosh"),
            new Artist(120, "Pink Floyd"),
            new Artist(121, "Planet Hemp"),
            new Artist(122, "R.E.M. Feat. Kate Pearson"),
            new Artist(123, "R.E.M. Feat. KRS-One"),
            new Artist(124, "R.E.M."),
            new Artist(125, "Raimundos"),
            new Artist(126, "Raul Seixas"),
            new Artist(127, "Red Hot Chili Peppers"),
            new Artist(128, "Rush"),
            new Artist(129, "Simply Red"),
            new Artist(130, "Skank"),
            new Artist(131, "Smashing Pumpkins"),
            new Artist(132, "Soundgarden"),
            new Artist(133, "Stevie Ray Vaughan & Double Trouble"),
            new Artist(134, "Stone Temple Pilots"),
            new Artist(135, "System Of A Down"),
            new Artist(136, "Terry Bozzio, Tony Levin & Steve Stevens"),
            new Artist(137, "The Black Crowes"),
            new Artist(138, "The Clash"),
            new Artist(139, "The Cult"),
            new Artist(140, "The Doors"),
            new Artist(141, "The Police"),
            new Artist(142, "The Rolling Stones"),
            new Artist(143, "The Tea Party"),
            new Artist(144, "The Who"),
            new Artist(145, "Tim Maia"),
            new Artist(146, "Titãs"),
            new Artist(147, "Battlestar Galactica"),
            new Artist(148, "Heroes"),
            new Artist(149, "Lost"),
            new Artist(150, "U2"),
            new Artist(151, "UB40"),
            new Artist(152, "Van Halen"),
            new Artist(153, "Velvet Revolver"),
            new Artist(154, "Whitesnake"),
            new Artist(155, "Zeca Pagodinho"),
            new Artist(156, "The Office"),
            new Artist(157, "Dread Zeppelin"),
            new Artist(158, "Battlestar Galactica (Classic)"),
            new Artist(159, "Aquaman"),
            new Artist(160, "Christina Aguilera featuring BigElf"),
            new Artist(161, "Aerosmith & Sierra Leone's Refugee Allstars"),
            new Artist(162, "Los Lonely Boys"),
            new Artist(163, "Corinne Bailey Rae"),
            new Artist(164, "Dhani Harrison & Jakob Dylan"),
            new Artist(165, "Jackson Browne"),
            new Artist(166, "Avril Lavigne"),
            new Artist(167, "Big & Rich"),
            new Artist(168, "Youssou N'Dour"),
            new Artist(169, "Black Eyed Peas"),
            new Artist(170, "Jack Johnson"),
            new Artist(171, "Ben Harper"),
            new Artist(172, "Snow Patrol"),
            new Artist(173, "Matisyahu"),
            new Artist(174, "The Postal Service"),
            new Artist(175, "Jaguares"),
            new Artist(176, "The Flaming Lips"),
            new Artist(177, "Jack's Mannequin & Mick Fleetwood"),
            new Artist(178, "Regina Spektor"),
            new Artist(179, "Scorpions"),
            new Artist(180, "House Of Pain"),
            new Artist(181, "Xis"),
            new Artist(182, "Nega Gizza"),
            new Artist(183, "Gustavo & Andres Veiga & Salazar"),
            new Artist(184, "Rodox"),
            new Artist(185, "Charlie Brown Jr."),
            new Artist(186, "Pedro Luís E A Parede"),
            new Artist(187, "Los Hermanos"),
            new Artist(188, "Mundo Livre S/A"),
            new Artist(189, "Otto"),
            new Artist(190, "Instituto"),
            new Artist(191, "Nação Zumbi"),
            new Artist(192, "DJ Dolores & Orchestra Santa Massa"),
            new Artist(193, "Seu Jorge"),
            new Artist(194, "Sabotage E Instituto"),
            new Artist(195, "Stereo Maracana"),
            new Artist(196, "Cake"),
            new Artist(197, "Aisha Duo"),
            new Artist(198, "Habib Koité and Bamada"),
            new Artist(199, "Karsh Kale"),
            new Artist(200, "The Posies"),
            new Artist(201, "Luciana Souza/Romero Lubambo"),
            new Artist(202, "Aaron Goldberg"),
            new Artist(203, "Nicolaus Esterhazy Sinfonia"),
            new Artist(204, "Temple of the Dog"),
            new Artist(205, "Chris Cornell"),
            new Artist(206, "Alberto Turco & Nova Schola Gregoriana"),
            new Artist(207, "Richard Marlow & The Choir of Trinity College, Cambridge"),
            new Artist(208, "English Concert & Trevor Pinnock"),
            new Artist(209, "Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker"),
            new Artist(210, "Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer"),
            new Artist(211, "Wilhelm Kempff"),
            new Artist(212, "Yo-Yo Ma"),
            new Artist(213, "Scholars Baroque Ensemble"),
            new Artist(214, "Academy of St. Martin in the Fields & Sir Neville Marriner"),
            new Artist(215, "Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner"),
            new Artist(216, "Berliner Philharmoniker, Claudio Abbado & Sabine Meyer"),
            new Artist(217, "Royal Philharmonic Orchestra & Sir Thomas Beecham"),
            new Artist(218, "Orchestre Révolutionnaire et Romantique & John Eliot Gardiner"),
            new Artist(219, "Britten Sinfonia, Ivor Bolton & Lesley Garrett"),
            new Artist(220, "Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti"),
            new Artist(221, "Sir Georg Solti & Wiener Philharmoniker"),
            new Artist(222, "Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair"),
            new Artist(223, "London Symphony Orchestra & Sir Charles Mackerras"),
            new Artist(224, "Barry Wordsworth & BBC Concert Orchestra"),
            new Artist(225, "Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker"),
            new Artist(226, "Eugene Ormandy"),
            new Artist(227, "Luciano Pavarotti"),
            new Artist(228, "Leonard Bernstein & New York Philharmonic"),
            new Artist(229, "Boston Symphony Orchestra & Seiji Ozawa"),
            new Artist(230, "Aaron Copland & London Symphony Orchestra"),
            new Artist(231, "Ton Koopman"),
            new Artist(232, "Sergei Prokofiev & Yuri Temirkanov"),
            new Artist(233, "Chicago Symphony Orchestra & Fritz Reiner"),
            new Artist(234, "Orchestra of The Age of Enlightenment"),
            new Artist(235, "Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra"),
            new Artist(236, "James Levine"),
            new Artist(237, "Berliner Philharmoniker & Hans Rosbaud"),
            new Artist(238, "Maurizio Pollini"),
            new Artist(239, "Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett"),
            new Artist(240, "Gustav Mahler"),
            new Artist(241, "Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos"),
            new Artist(242, "Edo de Waart & San Francisco Symphony"),
            new Artist(243, "Antal Doráti & London Symphony Orchestra"),
            new Artist(244, "Choir Of Westminster Abbey & Simon Preston"),
            new Artist(245, "Michael Tilson Thomas & San Francisco Symphony"),
            new Artist(246, "Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker"),
            new Artist(247, "The King's Singers"),
            new Artist(248, "Berliner Philharmoniker & Herbert Von Karajan"),
            new Artist(249, "Sir Georg Solti, Sumi Jo & Wiener Philharmoniker"),
            new Artist(250, "Christopher O'Riley"),
            new Artist(251, "Fretwork"),
            new Artist(252, "Amy Winehouse"),
            new Artist(253, "Calexico"),
            new Artist(254, "Otto Klemperer & Philharmonia Orchestra"),
            new Artist(255, "Yehudi Menuhin"),
            new Artist(256, "Philharmonia Orchestra & Sir Neville Marriner"),
            new Artist(257, "Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart"),
            new Artist(258, "Les Arts Florissants & William Christie"),
            new Artist(259, "The 12 Cellists of The Berlin Philharmonic"),
            new Artist(260, "Adrian Leaper & Doreen de Feis"),
            new Artist(261, "Roger Norrington, London Classical Players"),
            new Artist(262, "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
            new Artist(263, "Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir"),
            new Artist(264, "Kent Nagano and Orchestre de l'Opéra de Lyon"),
            new Artist(265, "Julian Bream"),
            new Artist(266, "Martin Roscoe"),
            new Artist(267, "Göteborgs Symfoniker & Neeme Järvi"),
            new Artist(268, "Itzhak Perlman"),
            new Artist(269, "Michele Campanella"),
            new Artist(270, "Gerald Moore"),
            new Artist(271, "Mela Tenenbaum, Pro Musica Prague & Richard Kapp"),
            new Artist(272, "Emerson String Quartet"),
            new Artist(273, "C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu"),
            new Artist(274, "Nash Ensemble"),
            new Artist(275, "Philip Glass Ensemble")
        };
    }
}
