using System;
using System.Collections.Generic;
using System.Text;

namespace DataSources
{
    public static class ListAlbumsData
    {
        public static List<Album> ListAlbums = new List<Album>
        {
            new Album(1, "For Those About To Rock We Salute You"),
            new Album(2, "Balls to the Wall"),
            new Album(3, "Restless and Wild"),
            new Album(4, "Let There Be Rock"),
            new Album(5, "Big Ones"),
            new Album(6, "Jagged Little Pill"),
            new Album(7, "Facelift"),
            new Album(8, "Warner 25 Anos"),
            new Album(9, "Plays Metallica By Four Cellos"),
            new Album(10, "Audioslave"),
            new Album(11, "Out Of Exile"),
            new Album(12, "BackBeat Soundtrack"),
            new Album(13, "The Best Of Billy Cobham"),
            new Album(14, "Alcohol Fueled Brewtality Live! [Disc 1]"),
            new Album(15, "Alcohol Fueled Brewtality Live! [Disc 2]"),
            new Album(16, "Black Sabbath"),
            new Album(17, "Black Sabbath Vol. 4 (Remaster)"),
            new Album(18, "Body Count"),
            new Album(19, "Chemical Wedding"),
            new Album(20, "The Best Of Buddy Guy - The Millenium Collection"),
            new Album(21, "Prenda Minha"),
            new Album(22, "Sozinho Remix Ao Vivo"),
            new Album(23, "Minha Historia"),
            new Album(24, "Afrociberdelia"),
            new Album(25, "Da Lama Ao Caos"),
            new Album(26, "Acústico MTV [Live]"),
            new Album(27, "Cidade Negra - Hits"),
            new Album(28, "Na Pista"),
            new Album(29, "Axé Bahia 2001"),
            new Album(30, "BBC Sessions [Disc 1] [Live]"),
            new Album(31, "Bongo Fury"),
            new Album(32, "Carnaval 2001"),
            new Album(33, "Chill: Brazil (Disc 1)"),
            new Album(34, "Chill: Brazil (Disc 2)"),
            new Album(35, "Garage Inc. (Disc 1)"),
            new Album(36, "Greatest Hits II"),
            new Album(37, "Greatest Kiss"),
            new Album(38, "Heart of the Night"),
            new Album(39, "International Superhits"),
            new Album(40, "Into The Light"),
            new Album(41, "Meus Momentos"),
            new Album(42, "Minha História"),
            new Album(43, "MK III The Final Concerts [Disc 1]"),
            new Album(44, "Physical Graffiti [Disc 1]"),
            new Album(45, "Sambas De Enredo 2001"),
            new Album(46, "Supernatural"),
            new Album(47, "The Best of Ed Motta"),
            new Album(48, "The Essential Miles Davis [Disc 1]"),
            new Album(49, "The Essential Miles Davis [Disc 2]"),
            new Album(50, "The Final Concerts (Disc 2)"),
            new Album(51, "Up An' Atom"),
            new Album(52, "Vinícius De Moraes - Sem Limite"),
            new Album(53, "Vozes do MPB"),
            new Album(54, "Chronicle, Vol. 1"),
            new Album(55, "Chronicle, Vol. 2"),
            new Album(56, "Cássia Eller - Coleção Sem Limite [Disc 2]"),
            new Album(57, "Cássia Eller - Sem Limite [Disc 1]"),
            new Album(58, "Come Taste The Band"),
            new Album(59, "Deep Purple In Rock"),
            new Album(60, "Fireball"),
            new Album(61, "Knocking at Your Back Door: The Best Of Deep Purple in the 80's"),
            new Album(62, "Machine Head"),
            new Album(63, "Purpendicular"),
            new Album(64, "Slaves And Masters"),
            new Album(65, "Stormbringer"),
            new Album(66, "The Battle Rages On"),
            new Album(67, "Vault: Def Leppard's Greatest Hits"),
            new Album(68, "Outbreak"),
            new Album(69, "Djavan Ao Vivo - Vol. 02"),
            new Album(70, "Djavan Ao Vivo - Vol. 1"),
            new Album(71, "Elis Regina-Minha História"),
            new Album(72, "The Cream Of Clapton"),
            new Album(73, "Unplugged"),
            new Album(74, "Album Of The Year"),
            new Album(75, "Angel Dust"),
            new Album(76, "King For A Day Fool For A Lifetime"),
            new Album(77, "The Real Thing"),
            new Album(78, "Deixa Entrar"),
            new Album(79, "In Your Honor [Disc 1]"),
            new Album(80, "In Your Honor [Disc 2]"),
            new Album(81, "One By One"),
            new Album(82, "The Colour And The Shape"),
            new Album(83, "My Way: The Best Of Frank Sinatra [Disc 1]"),
            new Album(84, "Roda De Funk"),
            new Album(85, "As Canções de Eu Tu Eles"),
            new Album(86, "Quanta Gente Veio Ver (Live)"),
            new Album(87, "Quanta Gente Veio ver--Bônus De Carnaval"),
            new Album(88, "Faceless"),
            new Album(89, "American Idiot"),
            new Album(90, "Appetite for Destruction"),
            new Album(91, "Use Your Illusion I"),
            new Album(92, "Use Your Illusion II"),
            new Album(93, "Blue Moods"),
            new Album(94, "A Matter of Life and Death"),
            new Album(95, "A Real Dead One"),
            new Album(96, "A Real Live One"),
            new Album(97, "Brave New World"),
            new Album(98, "Dance Of Death"),
            new Album(99, "Fear Of The Dark"),
            new Album(100, "Iron Maiden"),
            new Album(101, "Killers"),
            new Album(102, "Live After Death"),
            new Album(103, "Live At Donington 1992 (Disc 1)"),
            new Album(104, "Live At Donington 1992 (Disc 2)"),
            new Album(105, "No Prayer For The Dying"),
            new Album(106, "Piece Of Mind"),
            new Album(107, "Powerslave"),
            new Album(108, "Rock In Rio [CD1]"),
            new Album(109, "Rock In Rio [CD2]"),
            new Album(110, "Seventh Son of a Seventh Son"),
            new Album(111, "Somewhere in Time"),
            new Album(112, "The Number of The Beast"),
            new Album(113, "The X Factor"),
            new Album(114, "Virtual XI"),
            new Album(115, "Sex Machine"),
            new Album(116, "Emergency On Planet Earth"),
            new Album(117, "Synkronized"),
            new Album(118, "The Return Of The Space Cowboy"),
            new Album(119, "Get Born"),
            new Album(120, "Are You Experienced?"),
            new Album(121, "Surfing with the Alien (Remastered)"),
            new Album(122, "Jorge Ben Jor 25 Anos"),
            new Album(123, "Jota Quest-1995"),
            new Album(124, "Cafezinho"),
            new Album(125, "Living After Midnight"),
            new Album(126, "Unplugged [Live]"),
            new Album(127, "BBC Sessions [Disc 2] [Live]"),
            new Album(128, "Coda"),
            new Album(129, "Houses Of The Holy"),
            new Album(130, "In Through The Out Door"),
            new Album(131, "IV"),
            new Album(132, "Led Zeppelin I"),
            new Album(133, "Led Zeppelin II"),
            new Album(134, "Led Zeppelin III"),
            new Album(135, "Physical Graffiti [Disc 2]"),
            new Album(136, "Presence"),
            new Album(137, "The Song Remains The Same (Disc 1)"),
            new Album(138, "The Song Remains The Same (Disc 2)"),
            new Album(139, "A TempestadeTempestade Ou O Livro Dos Dias"),
            new Album(140, "Mais Do Mesmo"),
            new Album(141, "Greatest Hits"),
            new Album(142, "Lulu Santos - RCA 100 Anos De Música - Álbum 01"),
            new Album(143, "Lulu Santos - RCA 100 Anos De Música - Álbum 02"),
            new Album(144, "Misplaced Childhood"),
            new Album(145, "Barulhinho Bom"),
            new Album(146, "Seek And Shall Find: More Of The Best (1963-1981)"),
            new Album(147, "The Best Of Men At Work"),
            new Album(148, "Black Album"),
            new Album(149, "Garage Inc. (Disc 2)"),
            new Album(150, "Kill 'Em All"),
            new Album(151, "Load"),
            new Album(152, "Master Of Puppets"),
            new Album(153, "ReLoad"),
            new Album(154, "Ride The Lightning"),
            new Album(155, "St. Anger"),
            new Album(156, "...And Justice For All"),
            new Album(157, "Miles Ahead"),
            new Album(158, "Milton Nascimento Ao Vivo"),
            new Album(159, "Minas"),
            new Album(160, "Ace Of Spades"),
            new Album(161, "Demorou..."),
            new Album(162, "Motley Crue Greatest Hits"),
            new Album(163, "From The Muddy Banks Of The Wishkah [Live]"),
            new Album(164, "Nevermind"),
            new Album(165, "Compositores"),
            new Album(166, "Olodum"),
            new Album(167, "Acústico MTV"),
            new Album(168, "Arquivo II"),
            new Album(169, "Arquivo Os Paralamas Do Sucesso"),
            new Album(170, "Bark at the Moon (Remastered)"),
            new Album(171, "Blizzard of Ozz"),
            new Album(172, "Diary of a Madman (Remastered)"),
            new Album(173, "No More Tears (Remastered)"),
            new Album(174, "Tribute"),
            new Album(175, "Walking Into Clarksdale"),
            new Album(176, "Original Soundtracks 1"),
            new Album(177, "The Beast Live"),
            new Album(178, "Live On Two Legs [Live]"),
            new Album(179, "Pearl Jam"),
            new Album(180, "Riot Act"),
            new Album(181, "Ten"),
            new Album(182, "Vs."),
            new Album(183, "Dark Side Of The Moon"),
            new Album(184, "Os Cães Ladram Mas A Caravana Não Pára"),
            new Album(185, "Greatest Hits I"),
            new Album(186, "News Of The World"),
            new Album(187, "Out Of Time"),
            new Album(188, "Green"),
            new Album(189, "New Adventures In Hi-Fi"),
            new Album(190, "The Best Of R.E.M.: The IRS Years"),
            new Album(191, "Cesta Básica"),
            new Album(192, "Raul Seixas"),
            new Album(193, "Blood Sugar Sex Magik"),
            new Album(194, "By The Way"),
            new Album(195, "Californication"),
            new Album(196, "Retrospective I (1974-1980)"),
            new Album(197, "Santana - As Years Go By"),
            new Album(198, "Santana Live"),
            new Album(199, "Maquinarama"),
            new Album(200, "O Samba Poconé"),
            new Album(201, "Judas 0: B-Sides and Rarities"),
            new Album(202, "Rotten Apples: Greatest Hits"),
            new Album(203, "A-Sides"),
            new Album(204, "Morning Dance"),
            new Album(205, "In Step"),
            new Album(206, "Core"),
            new Album(207, "Mezmerize"),
            new Album(208, "[1997] Black Light Syndrome"),
            new Album(209, "Live [Disc 1]"),
            new Album(210, "Live [Disc 2]"),
            new Album(211, "The Singles"),
            new Album(212, "Beyond Good And Evil"),
            new Album(213, "Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]"),
            new Album(214, "The Doors"),
            new Album(215, "The Police Greatest Hits"),
            new Album(216, "Hot Rocks, 1964-1971 (Disc 1)"),
            new Album(217, "No Security"),
            new Album(218, "Voodoo Lounge"),
            new Album(219, "Tangents"),
            new Album(220, "Transmission"),
            new Album(221, "My Generation - The Very Best Of The Who"),
            new Album(222, "Serie Sem Limite (Disc 1)"),
            new Album(223, "Serie Sem Limite (Disc 2)"),
            new Album(224, "Acústico"),
            new Album(225, "Volume Dois"),
            new Album(226, "Battlestar Galactica: The Story So Far"),
            new Album(227, "Battlestar Galactica, Season 3"),
            new Album(228, "Heroes, Season 1"),
            new Album(229, "Lost, Season 3"),
            new Album(230, "Lost, Season 1"),
            new Album(231, "Lost, Season 2"),
            new Album(232, "Achtung Baby"),
            new Album(233, "All That You Can't Leave Behind"),
            new Album(234, "B-Sides 1980-1990"),
            new Album(235, "How To Dismantle An Atomic Bomb"),
            new Album(236, "Pop"),
            new Album(237, "Rattle And Hum"),
            new Album(238, "The Best Of 1980-1990"),
            new Album(239, "War"),
            new Album(240, "Zooropa"),
            new Album(241, "UB40 The Best Of - Volume Two [UK]"),
            new Album(242, "Diver Down"),
            new Album(243, "The Best Of Van Halen, Vol. I"),
            new Album(244, "Van Halen"),
            new Album(245, "Van Halen III"),
            new Album(246, "Contraband"),
            new Album(247, "Vinicius De Moraes"),
            new Album(248, "Ao Vivo [IMPORT]"),
            new Album(249, "The Office, Season 1"),
            new Album(250, "The Office, Season 2"),
            new Album(251, "The Office, Season 3"),
            new Album(252, "Un-Led-Ed"),
            new Album(253, "Battlestar Galactica (Classic), Season 1"),
            new Album(254, "Aquaman"),
            new Album(255, "Instant Karma: The Amnesty International Campaign to Save Darfur"),
            new Album(256, "Speak of the Devil"),
            new Album(257, "20th Century Masters - The Millennium Collection: The Best of Scorpions"),
            new Album(258, "House of Pain"),
            new Album(259, "Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro"),
            new Album(260, "Cake: B-Sides and Rarities"),
            new Album(261, "LOST, Season 4"),
            new Album(262, "Quiet Songs"),
            new Album(263, "Muso Ko"),
            new Album(264, "Realize"),
            new Album(265, "Every Kind of Light"),
            new Album(266, "Duos II"),
            new Album(267, "Worlds"),
            new Album(268, "The Best of Beethoven"),
            new Album(269, "Temple of the Dog"),
            new Album(270, "Carry On"),
            new Album(271, "Revelations"),
            new Album(272, "Adorate Deum: Gregorian Chant from the Proper of the Mass"),
            new Album(273, "Allegri: Miserere"),
            new Album(274, "Pachelbel: Canon & Gigue"),
            new Album(275, "Vivaldi: The Four Seasons"),
            new Album(276, "Bach: Violin Concertos"),
            new Album(277, "Bach: Goldberg Variations"),
            new Album(278, "Bach: The Cello Suites"),
            new Album(279, "Handel: The Messiah (Highlights)"),
            new Album(280, "The World of Classical Favourites"),
            new Album(281, "Sir Neville Marriner: A Celebration"),
            new Album(282, "Mozart: Wind Concertos"),
            new Album(283, "Haydn: Symphonies 99 - 104"),
            new Album(284, "Beethoven: Symhonies Nos. 5 & 6"),
            new Album(285, "A Soprano Inspired"),
            new Album(286, "Great Opera Choruses"),
            new Album(287, "Wagner: Favourite Overtures"),
            new Album(288, "Fauré: Requiem, Ravel: Pavane & Others"),
            new Album(289, "Tchaikovsky: The Nutcracker"),
            new Album(290, "The Last Night of the Proms"),
            new Album(291, "Puccini: Madama Butterfly - Highlights"),
            new Album(292, "Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies"),
            new Album(293, "Pavarotti's Opera Made Easy"),
            new Album(294, "Great Performances - Barber's Adagio and Other Romantic Favorites for Strings"),
            new Album(295, "Carmina Burana"),
            new Album(296, "A Copland Celebration, Vol. I"),
            new Album(297, "Bach: Toccata & Fugue in D Minor"),
            new Album(298, "Prokofiev: Symphony No.1"),
            new Album(299, "Scheherazade"),
            new Album(300, "Bach: The Brandenburg Concertos"),
            new Album(301, "Chopin: Piano Concertos Nos. 1 & 2"),
            new Album(302, "Mascagni: Cavalleria Rusticana"),
            new Album(303, "Sibelius: Finlandia"),
            new Album(304, "Beethoven Piano Sonatas: Moonlight & Pastorale"),
            new Album(305, "Great Recordings of the Century - Mahler: Das Lied von der Erde"),
            new Album(306, "Elgar: Cello Concerto & Vaughan Williams: Fantasias"),
            new Album(307, "Adams, John: The Chairman Dances"),
            new Album(308, "Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory"),
            new Album(309, "Palestrina: Missa Papae Marcelli & Allegri: Miserere"),
            new Album(310, "Prokofiev: Romeo & Juliet"),
            new Album(311, "Strauss: Waltzes"),
            new Album(312, "Berlioz: Symphonie Fantastique"),
            new Album(313, "Bizet: Carmen Highlights"),
            new Album(314, "English Renaissance"),
            new Album(315, "Handel: Music for the Royal Fireworks (Original Version 1749)"),
            new Album(316, "Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande"),
            new Album(317, "Mozart Gala: Famous Arias"),
            new Album(318, "SCRIABIN: Vers la flamme"),
            new Album(319, "Armada: Music from the Courts of England and Spain"),
            new Album(320, "Mozart: Symphonies Nos. 40 & 41"),
            new Album(321, "Back to Black"),
            new Album(322, "Frank"),
            new Album(323, "Carried to Dust (Bonus Track Version)"),
            new Album(324, "Beethoven: Symphony No. 6 'Pastoral' Etc."),
            new Album(325, "Bartok: Violin & Viola Concertos"),
            new Album(326, "Mendelssohn: A Midsummer Night's Dream"),
            new Album(327, "Bach: Orchestral Suites Nos. 1 - 4"),
            new Album(328, "Charpentier: Divertissements, Airs & Concerts"),
            new Album(329, "South American Getaway"),
            new Album(330, "Górecki: Symphony No. 3"),
            new Album(331, "Purcell: The Fairy Queen"),
            new Album(332, "The Ultimate Relexation Album"),
            new Album(333, "Purcell: Music for the Queen Mary"),
            new Album(334, "Weill: The Seven Deadly Sins"),
            new Album(335, "J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro"),
            new Album(336, "Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps"),
            new Album(337, "Szymanowski: Piano Works, Vol. 1"),
            new Album(338, "Nielsen: The Six Symphonies"),
            new Album(339, "Great Recordings of the Century: Paganini's 24 Caprices"),
            new Album(340, "Liszt - 12 Études D'Execution Transcendante"),
            new Album(341, "Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder"),
            new Album(342, "Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3"),
            new Album(343, "Respighi:Pines of Rome"),
            new Album(344, "Schubert: The Late String Quartets & String Quintet (3 CD's)"),
            new Album(345, "Monteverdi: L'Orfeo"),
            new Album(346, "Mozart: Chamber Music"),
            new Album(347, "Koyaanisqatsi (Soundtrack from the Motion Picture)")
        };
    }
}
